#!/usr/bin/env bash
# Configure your Nginx server so that 
# /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start
new_url="https://www.linkedin.com/in/shannel-bejarano-022801215/"
redi="/redirect_me"
content="\tlocation ${redi} {\n\t\treturn 301 ${new_url};\n\t}"
path="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _;/ a\\${content}" ${path}
sudo service nginx restart
