#!/usr/bin/env bash
#clock loop

hours=0

while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    mins=1
    while [ $mins -le 59 ]
    do
        echo "$mins"
        ((mins++))
    done
((hours++))
done
