#!/usr/bin/env bash
#configures an Ubuntu server
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.old
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.old
echo "$ (cat ~ / hosts.old)"> / etc / hosts
